services:
  backend:
    build:
      context: ./Backend
    container_name: money-country-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env

  frontend:
    build:
      context: ./Frontend
    container_name: money-country-frontend
    restart: unless-stopped
    ports:
      - "5173:80"