name: Money Country CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Check Node and npm versions
        run: |
          node -v
          npm -v

      - name: Install backend dependencies
        working-directory: ./Backend
        run: npm ci

      - name: Install frontend dependencies
        working-directory: ./Frontend
        run: |
          npm ci
          npm install @rolldown/binding-linux-x64-gnu@1.0.0-rc.15 --no-save --force
          npm install lightningcss-linux-x64-gnu --no-save --force
          
      - name: Build frontend
        working-directory: ./Frontend
        run: npm run build

      - name: Build backend Docker image
        run: docker build -t money-country-backend ./Backend

      - name: Build frontend Docker image
        run: docker build -t money-country-frontend ./Frontend
